/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKEXTRACT_ELF_HEADER_H
#define _MOCKEXTRACT_ELF_HEADER_H

#include "../tests/Unity/src/unity.h"
#include "extract_elf_header.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 ||                                                            \
    (__GNUC__ == 4 &&                                                          \
     (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockextract_elf_header_Init(void);
void Mockextract_elf_header_Destroy(void);
void Mockextract_elf_header_Verify(void);

#define extract_elf_informations_Expect(filename, header_informations)         \
  TEST_FAIL_MESSAGE("extract_elf_informations requires _ExpectAndReturn");
#define extract_elf_informations_ExpectAndReturn(                              \
    filename, header_informations, cmock_retval)                               \
  extract_elf_informations_CMockExpectAndReturn(                               \
      __LINE__, filename, header_informations, cmock_retval)
void extract_elf_informations_CMockExpectAndReturn(
    UNITY_LINE_TYPE cmock_line, char *filename, Elf32_Ehdr *header_informations,
    bool cmock_to_return);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 ||                                                            \
    (__GNUC__ == 4 &&                                                          \
     (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
