/* AUTOGENERATED FILE. DO NOT EDIT. */
#include "../include/Mockextract_elf_header.h"
#include "../tests/CMock-2.6.0/src/cmock.h"
#include <setjmp.h>
#include <stdlib.h>
#include <string.h>

static const char *CMockString_extract_elf_informations =
    "extract_elf_informations";
static const char *CMockString_filename = "filename";
static const char *CMockString_header_informations = "header_informations";

typedef struct _CMOCK_extract_elf_informations_CALL_INSTANCE {
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;
  char *Expected_filename;
  Elf32_Ehdr *Expected_header_informations;

} CMOCK_extract_elf_informations_CALL_INSTANCE;

static struct Mockextract_elf_headerInstance {
  CMOCK_MEM_INDEX_TYPE extract_elf_informations_CallInstance;
} Mock;

void Mockextract_elf_header_Verify(void) {
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.extract_elf_informations_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance) {
    UNITY_SET_DETAIL(CMockString_extract_elf_informations);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockextract_elf_header_Init(void) { Mockextract_elf_header_Destroy(); }

void Mockextract_elf_header_Destroy(void) {
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

bool extract_elf_informations(char *filename, Elf32_Ehdr *header_informations) {
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_extract_elf_informations_CALL_INSTANCE *cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_extract_elf_informations);
  cmock_call_instance =
      (CMOCK_extract_elf_informations_CALL_INSTANCE *)CMock_Guts_GetAddressFor(
          Mock.extract_elf_informations_CallInstance);
  Mock.extract_elf_informations_CallInstance =
      CMock_Guts_MemNext(Mock.extract_elf_informations_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line,
                             CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_extract_elf_informations,
                      CMockString_filename);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_filename,
                                   filename, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_extract_elf_informations,
                      CMockString_header_informations);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(
        (void *)(cmock_call_instance->Expected_header_informations),
        (void *)(header_informations), sizeof(Elf32_Ehdr), cmock_line,
        CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_extract_elf_informations(
    CMOCK_extract_elf_informations_CALL_INSTANCE *cmock_call_instance,
    char *filename, Elf32_Ehdr *header_informations);
void CMockExpectParameters_extract_elf_informations(
    CMOCK_extract_elf_informations_CALL_INSTANCE *cmock_call_instance,
    char *filename, Elf32_Ehdr *header_informations) {
  cmock_call_instance->Expected_filename = filename;
  cmock_call_instance->Expected_header_informations = header_informations;
}

void extract_elf_informations_CMockExpectAndReturn(
    UNITY_LINE_TYPE cmock_line, char *filename, Elf32_Ehdr *header_informations,
    bool cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index =
      CMock_Guts_MemNew(sizeof(CMOCK_extract_elf_informations_CALL_INSTANCE));
  CMOCK_extract_elf_informations_CALL_INSTANCE *cmock_call_instance =
      (CMOCK_extract_elf_informations_CALL_INSTANCE *)CMock_Guts_GetAddressFor(
          cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line,
                             CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.extract_elf_informations_CallInstance = CMock_Guts_MemChain(
      Mock.extract_elf_informations_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_extract_elf_informations(cmock_call_instance, filename,
                                                 header_informations);
  cmock_call_instance->ReturnVal = cmock_to_return;
}
